[package]
name = "application_state"
version = "0.1.0"
edition = "2021"
authors = ["JoonHo Son <joonho.son@me.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
